/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Array: typeof import('./components/Array/index.vue')['default']
    BarItem: typeof import('./components/Array/BarItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderInput: typeof import('./components/Ui/SliderInput.vue')['default']
  }
}
