name: Tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "package-lock.json"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "package-lock.json"
      - ".github/workflows/tests.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 18
          cache: "npm"

      - uses: actions/cache@v4.2.2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-chromium-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Run unit tests
        run: npm run test:ci

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y libasound2t64
          npx playwright install --with-deps chromium

      - name: Build
        run: npm run build

      - name: Run e2e tests
        run: npm run test:ci-e2e --project="chromium"

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test-results-chromium
          path: |
            playwright-report/
            test-results/
            coverage/

      - name: Coverage
        if: success()
        uses: davelosert/vitest-coverage-report-action@v2.8.0
